INSERT INTO User VALUES(-1, SYSDATE(), 'AB');
INSERT INTO User VALUES(-2, SYSDATE(), 'Jill');
INSERT INTO User VALUES(-3, SYSDATE(), 'Jam');

INSERT INTO Post VALUES(-1, 'My First Post', -1);
INSERT INTO Post VALUES(-2, 'My Second Post', -1);